version: '3'
services:

  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    restart: always
    depends_on:
      - todoback

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    restart: always
    depends_on:
      - todofront
      - todoback